export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES';

export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const REQUEST_ARTICLES_SUCCESS = 'REQUEST_ARTICLES_SUCCESS';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
